FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD="secret"
ENV MYSQL_DATABASE="bluecrew"
ENV MYSQL_USER="cats_admin"
ENV MYSQL_PASSWORD="cheezburger"

ADD ./schema/bluecrew_schema.sql /docker-entrypoint-initdb.d/.